import { Spell } from '../types/spell';

export const mockSpells: Spell[] = [
  {
    id: 'fireball',
    name: 'Fireball',
    level: 3,
    school: 'evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: {
      verbal: true,
      somatic: true,
      material: true,
    },
    materials: 'A tiny ball of bat guano and sulfur',
    duration: 'Instantaneous',
    description: 'A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame.',
    higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
    concentration: false,
    ritual: false,
    classes: ['wizard', 'sorcerer'],
    source: '5e Core Rules',
  },
  {
    id: 'shield',
    name: 'Shield',
    level: 1,
    school: 'abjuration',
    castingTime: '1 reaction',
    range: 'Self',
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    materials: '',
    duration: '1 round',
    description: 'An invisible barrier of magical force appears and protects you.',
    higherLevels: '',
    concentration: false,
    ritual: false,
    classes: ['wizard', 'sorcerer'],
    source: '5e Core Rules',
  },
  {
    id: 'detect-magic',
    name: 'Detect Magic',
    level: 1,
    school: 'divination',
    castingTime: '1 action',
    range: 'Self',
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    materials: '',
    duration: 'Concentration, up to 10 minutes',
    description: 'For the duration, you sense the presence of magic within 30 feet of you.',
    higherLevels: '',
    concentration: true,
    ritual: true,
    classes: ['wizard', 'bard', 'cleric', 'druid'],
    source: '5e Core Rules',
  },
  {
    id: 'healing-word',
    name: 'Healing Word',
    level: 1,
    school: 'evocation',
    castingTime: '1 bonus action',
    range: '60 feet',
    components: {
      verbal: true,
      somatic: false,
      material: false,
    },
    materials: '',
    duration: 'Instantaneous',
    description: 'A creature of your choice that you can see within range regains hit points.',
    higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d4 for each slot level above 1st.',
    concentration: false,
    ritual: false,
    classes: ['cleric', 'bard', 'druid'],
    source: '5e Core Rules',
  },
  {
    id: 'eldritch-blast',
    name: 'Eldritch Blast',
    level: 0,
    school: 'evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    materials: '',
    duration: 'Instantaneous',
    description: 'A beam of crackling energy streaks toward a creature within range.',
    higherLevels: '',
    concentration: false,
    ritual: false,
    classes: ['warlock'],
    source: '5e Core Rules',
  },
  {
    id: 'arcane-weapon',
    name: 'Arcane Weapon',
    level: 1,
    school: 'transmutation',
    castingTime: '1 bonus action',
    range: 'Self',
    components: {
      verbal: true,
      somatic: true,
      material: false,
    },
    materials: '',
    duration: 'Concentration, up to 1 hour',
    description: 'You channel arcane energy into one simple or martial weapon you are holding.',
    higherLevels: '',
    concentration: true,
    ritual: false,
    classes: ['artificer'],
    source: 'Deep Magic',
  },
];
