import { Tour, TourId } from '../types/tutorial';

export const TOURS: Record<TourId, Tour> = {
  'browse-spells': {
    id: 'browse-spells',
    name: 'Browse Spells',
    description: 'Search, filter, and add spells to your spellbooks',
    requiredView: 'browse',
    steps: [
      {
        id: 'browse-table',
        targetSelector: '.spell-table',
        title: 'Spell List',
        description: 'Browse all available D&D spells here. You can sort using the buttons above.',
        desktopDescription: 'Browse all D&D spells here. Click any column header to sort.',
        placement: 'top',
      },
      {
        id: 'browse-spell-details',
        targetSelector: '.spell-row',
        title: 'View Spell Details',
        description: 'Tap any spell to see its full details and description. Try it out!',
        desktopDescription: 'Click any spell to see its full description. Try it out!',
        placement: 'bottom',
        interactive: true,
      },
      {
        id: 'browse-filters',
        targetSelector: '.filter-header',
        title: 'Advanced Filters',
        description: 'There are tons of spells to pick from, so you can apply filters to the Spell table for spell level, school, class, and more.',
        placement: 'bottom',
      },
      {
        id: 'browse-search',
        targetSelector: '.search-input',
        title: 'Search Spells',
        description: 'You can also search for spells by name. Give it a shot! Try searching for "fire" to find spells like "Fire Bolt," "Fireball," "Faerie Fire" and so on.',
        placement: 'bottom',
        interactive: true,
      },
      {
        id: 'browse-checkbox',
        targetSelector: '.spell-table',
        desktopSelector: '.spell-row .checkbox-col input',
        title: 'Select Spells',
        description: 'Once you\'ve found spells that you like, you can select/deselect them by long-pressing or swiping to the side. Try it out!',
        desktopDescription: 'Once you\'ve found spells that you like, you can select/deselect them using the checkbox. Try it out!',
        placement: 'bottom',
        desktopPlacement: 'right',
        interactive: true,
      },
      {
        id: 'browse-select-all',
        targetSelector: '[data-testid="btn-select-all-mobile"]',
        title: 'Bulk Selection',
        description: 'You can also bulk select/deselect all visible spells at once. Great when combined with filters!',
        placement: 'bottom',
      },
      {
        id: 'browse-add',
        targetSelector: '[data-testid="btn-add-selected"]',
        title: 'Add to Spellbook',
        description: 'Finally, once you\'ve selected yours spells, click here to add them to a Spellbook. You\'ll choose which Spellbook to add to or create a brand new one.',
        placement: 'bottom',
      },
      {
        id: 'browse-complete',
        title: 'You\'re Ready!',
        description: 'Now you know how to browse and select spells. Try the "Manage Spellbooks" tour next to learn about creating spellbooks!',
        placement: 'center',
      },
    ],
  },
  'spellbooks-list': {
    id: 'spellbooks-list',
    name: 'Manage Spellbooks',
    description: 'Create, edit, and organize your spellbook collection',
    requiredView: 'spellbooks',
    steps: [
      {
        id: 'spellbooks-create',
        targetSelector: '[data-testid="btn-create-spellbook"]',
        title: 'Create a Spellbook',
        description: 'Start here! Create a new spellbook for your character or campaign. You can set spellcasting ability and stats.',
        placement: 'bottom',
      },
      {
        id: 'spellbooks-search',
        targetSelector: '.spellbook-search',
        title: 'Search Spellbooks',
        description: 'Have many spellbooks? Search by name to quickly find the one you need.',
        placement: 'bottom',
      },
      {
        id: 'spellbooks-list',
        targetSelector: '.spellbook-list-table',
        title: 'Your Spellbooks',
        description: 'Each row is a spellbook. Tap to open, or long-press for quick actions like edit and delete.',
        desktopDescription: 'Each row is a spellbook. Click a row to open it and manage its spells.',
        placement: 'top',
      },
      {
        id: 'spellbooks-import-export',
        targetSelector: '[data-testid="btn-export-spellbooks"]',
        title: 'Import & Export',
        description: 'Backup your spellbooks or share them with friends. Uses JSON format that can be re-imported anytime.',
        placement: 'bottom',
      },
      {
        id: 'spellbooks-complete',
        title: 'All Set!',
        description: 'Now you know how to manage spellbooks. Open a spellbook to learn about preparing spells and tracking spell slots!',
        placement: 'center',
      },
    ],
  },
  'spellbook-detail': {
    id: 'spellbook-detail',
    name: 'Spellbook Details',
    description: 'Prepare spells and manage your spellbook contents',
    requiredView: 'spellbook-detail',
    steps: [
      {
        id: 'detail-header',
        targetSelector: '.spellbook-detail-header',
        title: 'Spellbook Overview',
        description: 'Your spellbook\'s name and stats are shown here. Use the buttons to edit, copy, or delete this spellbook.',
        placement: 'bottom',
      },
      {
        id: 'detail-slots',
        targetSelector: '.spell-slots-display',
        title: 'Spell Slots',
        description: 'Track your available spell slots by level. Set these in the Edit menu to match your character.',
        placement: 'bottom',
      },
      {
        id: 'detail-spells',
        targetSelector: '.spellbook-table',
        title: 'Your Spells',
        description: 'All spells in this spellbook. Tap any spell for details, or use checkboxes to select multiple.',
        desktopDescription: 'All spells in this spellbook. Click any row to see full details and toggle prepared status.',
        placement: 'top',
      },
      {
        id: 'detail-prepared-toggle',
        targetSelector: '[data-testid="btn-prep-selected"]',
        title: 'Prepare Spells',
        description: 'Select spells using checkboxes, then click Prep to mark them as prepared. Prepared spells are highlighted in gold!',
        placement: 'bottom',
      },
      {
        id: 'detail-prepared-filter',
        targetSelector: '[data-testid="filter-prepared-only"]',
        title: 'Filter by Prepared',
        description: 'Toggle this to show only your prepared spells. Great for during gameplay when you need quick access.',
        placement: 'bottom',
      },
      {
        id: 'detail-remove',
        targetSelector: '[data-testid="btn-remove-selected"]',
        title: 'Remove Spells',
        description: 'Select spells and click Remove to take them out of this spellbook. You can always add them back later.',
        placement: 'bottom',
      },
      {
        id: 'detail-back',
        targetSelector: '[data-testid="back-to-spellbooks"]',
        title: 'Navigation',
        description: 'Click here to go back to your spellbook list when you\'re done.',
        placement: 'bottom',
      },
      {
        id: 'detail-complete',
        title: 'You\'re All Set!',
        description: 'You now know how to use The Spellbookery! Happy spellcasting!',
        placement: 'center',
      },
    ],
  },
};

export const TOUR_ORDER: TourId[] = [
  'browse-spells',
  'spellbooks-list',
  'spellbook-detail',
];
