import { Tour, TourId } from '../types/tutorial';

export const TOURS: Record<TourId, Tour> = {
  // Welcome Tour: End-to-end onboarding for new users
  // Covers Browse → Spellbook Detail → Spellbooks List in one continuous flow
  'welcome': {
    id: 'welcome',
    name: 'Welcome Tour',
    description: 'Complete introduction to The Spellbookery',
    requiredView: 'browse',
    steps: [
      // BROWSE PHASE
      {
        id: 'welcome-intro',
        title: 'Welcome to The Spellbookery!',
        description: 'This is your one-stop shop for D&D spellbook management. Let\'s take a quick tour of how things work, shall we?',
        placement: 'center',
      },
      {
        id: 'browse-table',
        targetSelector: '.spell-table',
        title: 'Browsing Spells',
        description: 'This is the Browse Spells table, where you can find all available D&D spells. Tap on a spell to see its full details and description.',
        desktopDescription: 'This is the Browse Spells table, where you can find all available D&D spells. Click on a spell to see its full details and description.',
        placement: 'top',
        mobilePlacement: 'top',
        interactive: true,
      },
      {
        id: 'browse-filters',
        targetSelector: '.filter-header',
        title: 'Advanced Filters',
        description: 'There are tons of spells to pick from, so you can search by Spell Name or narrow things down with filters for Spell Level, School, Class, and more.',
        placement: 'bottom',
        interactive: true,
      },
      {
        id: 'browse-checkbox',
        targetSelector: '.spell-table',
        desktopSelector: '.spell-row .checkbox-col input',
        title: 'Select Spells',
        description: 'Spells can be selected/deselected by long-pressing or swiping to the side. Give it a shot!',
        desktopDescription: 'Spells can be selected/deselected using the checkbox.',
        placement: 'bottom',
        desktopPlacement: 'right',
        interactive: true,
      },
      {
        id: 'browse-select-all',
        targetSelector: '[data-testid="btn-select-all-mobile"]',
        title: 'Bulk Selection',
        description: 'You can also bulk select/deselect all visible spells at once. Great when combined with filters!',
        placement: 'bottom',
      },
      {
        id: 'browse-add',
        targetSelector: '[data-testid="btn-add-selected"]',
        title: 'Add to Spellbook',
        description: 'Once you\'ve selected some spells, click here to save them to a brand new Spellbook or add them to an existing one.',
        placement: 'bottom',
      },
      // TRANSITION TO SPELLBOOK DETAIL
      {
        id: 'spellbook-transition',
        title: 'Inside a Spellbook',
        description: 'Now let\'s take a look at a spellbook. We\'ve already created one as an example for you to explore.',
        placement: 'center',
        beforeStep: 'navigate-to-spellbook-detail',
        requiredView: 'spellbook-detail',
      },
      // SPELLBOOK DETAIL PHASE
      {
        id: 'detail-header',
        targetSelector: '.spellbook-detail-header',
        title: 'Spellbook Overview',
        description: 'Your spellbook\'s name and basic stats are shown here. Use the buttons to edit stats, make a copy, or delete this spellbook.',
        placement: 'bottom',
        requiredView: 'spellbook-detail',
      },
      {
        id: 'detail-slots',
        targetSelector: '.spell-slots-display',
        title: 'Spell Slots',
        description: 'These show your total spell slots by level. Set these in the Edit menu to match your character.',
        placement: 'left',
        requiredView: 'spellbook-detail',
      },
      {
        id: 'detail-spells',
        targetSelector: '.spellbook-table',
        title: 'Your Spells',
        description: 'And here are the spells! Just like the Browse table, you can tap any spell for details, swipe to select, search, filter, etc.',
        desktopDescription: 'And here are the spells! Just like the Browse table, you can click any spell for details, check to select, search, filter, etc.',
        placement: 'top',
        requiredView: 'spellbook-detail',
        interactive: true,
      },
      {
        id: 'detail-prepared-toggle',
        targetSelector: '[data-testid="btn-prep-selected"]',
        title: 'Prepare Spells',
        description: 'You can also mark selected spells as Prepared. Prepared spells are highlighted in gold!',
        placement: 'right',
        requiredView: 'spellbook-detail',
      },
      {
        id: 'detail-prepared-filter',
        targetSelector: '[data-testid="filter-prepared-only"]',
        title: 'Filter by Prepared',
        description: 'Toggle this to show only your prepared spells. Great for during gameplay when you need quick access.',
        placement: 'bottom',
        requiredView: 'spellbook-detail',
        interactive: true,
      },
      {
        id: 'detail-remove',
        targetSelector: '[data-testid="btn-remove-selected"]',
        title: 'Remove Spells',
        description: 'Spells can also be removed from the spellbook if necessary. You can always add them back later from the Browse page.',
        placement: 'bottom',
        requiredView: 'spellbook-detail',
      },
      // TRANSITION TO SPELLBOOKS LIST
      {
        id: 'list-transition',
        title: 'Your Spellbook Collection',
        description: 'Finally, let\'s see how to manage all your spellbooks.',
        placement: 'center',
        beforeStep: 'navigate-to-spellbooks',
        requiredView: 'spellbooks',
      },
      // SPELLBOOKS LIST PHASE
      {
        id: 'spellbooks-list',
        targetSelector: '.spellbooks-table',
        title: 'Your Spellbooks',
        description: 'This table lists all your saved spellbooks. Tap one to open, or long-press for quick actions like copy and delete.',
        desktopDescription: 'This table lists all your saved spellbooks. Tap one to open, or use the button on the right for actions like Copy and Delete.',
        placement: 'top',
        mobilePlacement: 'top',
        requiredView: 'spellbooks',
      },
      {
        id: 'spellbooks-create',
        targetSelector: '[data-testid="btn-create-spellbook"]',
        title: 'Create a Spellbook',
        description: 'Create new spellbooks for new characters or campaigns. You can set spellcasting ability, attack modifier, and spell slots. Adding spells can be done later from the Browse Spells page.',
        placement: 'bottom',
        requiredView: 'spellbooks',
      },
      {
        id: 'spellbooks-search',
        targetSelector: '.spellbook-search',
        title: 'Search Spellbooks',
        description: 'Have lots of spellbooks? Search by name to quickly find the one you need.',
        placement: 'bottom',
        requiredView: 'spellbooks',
      },
      {
        id: 'spellbooks-import-export',
        targetSelector: '[data-testid="btn-export-spellbooks"]',
        title: 'Import & Export',
        description: 'Finally, you can export your spellbooks for backup or to share them with friends. Uses JSON format that can be re-imported anytime.',
        placement: 'bottom',
        requiredView: 'spellbooks',
      },
      {
        id: 'welcome-complete',
        title: 'You\'re All Set!',
        description: 'You now know how to use The Spellbookery! You can revisit these tours anytime from the Help menu. Happy spellcasting!',
        placement: 'center',
        requiredView: 'spellbooks',
      },
    ],
  },

  // Browse Spells Tour: Focused refresher on spell browsing (Help menu only)
  'browse-spells': {
    id: 'browse-spells',
    name: 'Browse Spells',
    description: 'Search, filter, and add spells to your spellbooks',
    requiredView: 'browse',
    steps: [
      {
        id: 'browse-table',
        targetSelector: '.spell-table',
        title: 'Spell List',
        description: 'Browse all available D&D spells here. You can sort using the buttons above the table.',
        desktopDescription: 'Browse all available D&D spells here. Click any column header to sort.',
        placement: 'top',
      },
      {
        id: 'browse-spell-details',
        targetSelector: '.spell-row',
        title: 'View Spell Details',
        description: 'Tap any spell to see its full details and description. Try it out!',
        desktopDescription: 'Click any spell to see its full description. Try it out!',
        placement: 'bottom',
        interactive: true,
      },
      {
        id: 'browse-filters',
        targetSelector: '.filter-header',
        title: 'Advanced Filters',
        description: 'There are tons of spells to pick from, so you can narrow things down with filters for spell Level, School, Class, and more.',
        placement: 'bottom',
      },
      {
        id: 'browse-search',
        targetSelector: '.search-input',
        title: 'Search Spells',
        description: 'You can also search for spells by name. Give it a shot! Try searching for "fire" to find spells like "Fire Bolt," "Fireball," "Faerie Fire" and so on.',
        placement: 'bottom',
        interactive: true,
      },
      {
        id: 'browse-checkbox',
        targetSelector: '.spell-table',
        desktopSelector: '.spell-row .checkbox-col input',
        title: 'Select Spells',
        description: 'Select and deselect spells by long-pressing or swiping to the side. Try it out!',
        desktopDescription: 'Select and deselect spells using the checkbox. Try it out!',
        placement: 'bottom',
        desktopPlacement: 'right',
        interactive: true,
      },
      {
        id: 'browse-select-all',
        targetSelector: '[data-testid="btn-select-all-mobile"]',
        title: 'Bulk Selection',
        description: 'You can also bulk select/deselect all visible spells at once. Great when combined with filters!',
        placement: 'bottom',
      },
      {
        id: 'browse-add',
        targetSelector: '[data-testid="btn-add-selected"]',
        title: 'Add to Spellbook',
        description: 'Finally, once you\'ve selected spells, click here to add them to a Spellbook. You can create a brand new Spellbook or add them to an existing one.',
        placement: 'bottom',
      },
      {
        id: 'browse-complete',
        title: 'You\'re Ready!',
        description: 'Now you know how to browse and select spells. Try the "Spellbooks" tour next to learn about organizing your spellbooks!',
        placement: 'center',
      },
    ],
  },

  // Spellbooks Tour: Focused refresher on spellbook management (Help menu only)
  'spellbooks': {
    id: 'spellbooks',
    name: 'Spellbooks',
    description: 'Create, organize, and prepare spells in your spellbooks',
    requiredView: 'spellbook-detail',
    steps: [
      // SPELLBOOK DETAIL PHASE
      {
        id: 'detail-intro',
        title: 'Inside a Spellbook',
        description: 'Let\'s explore what you can do inside a spellbook. We\'ve opened a sample spellbook for you.',
        placement: 'center',
      },
      {
        id: 'detail-header',
        targetSelector: '.spellbook-detail-header',
        title: 'Spellbook Overview',
        description: 'Your spellbook\'s name and stats are shown here. Use the buttons to edit, copy, or delete this spellbook.',
        placement: 'bottom',
      },
      {
        id: 'detail-slots',
        targetSelector: '.spell-slots-display',
        title: 'Spell Slots',
        description: 'Track your available spell slots by level. Set these in the Edit menu to match your character.',
        placement: 'bottom',
      },
      {
        id: 'detail-spells',
        targetSelector: '.spellbook-table',
        title: 'Your Spells',
        description: 'All spells in this spellbook. Tap any spell for details, or use checkboxes to select multiple.',
        desktopDescription: 'All spells in this spellbook. Click any row to see full details.',
        placement: 'top',
      },
      {
        id: 'detail-prepared-toggle',
        targetSelector: '[data-testid="btn-prep-selected"]',
        title: 'Prepare Spells',
        description: 'Select spells using checkboxes, then click Prep to mark them as prepared. Prepared spells are highlighted in gold!',
        placement: 'bottom',
      },
      {
        id: 'detail-prepared-filter',
        targetSelector: '[data-testid="filter-prepared-only"]',
        title: 'Filter by Prepared',
        description: 'Toggle this to show only your prepared spells. Great for during gameplay when you need quick access.',
        placement: 'bottom',
      },
      {
        id: 'detail-remove',
        targetSelector: '[data-testid="btn-remove-selected"]',
        title: 'Remove Spells',
        description: 'Select spells and click Remove to take them out of this spellbook. You can always add them back later from the Browse page.',
        placement: 'bottom',
      },
      // TRANSITION TO SPELLBOOKS LIST
      {
        id: 'list-transition',
        title: 'Your Spellbook Collection',
        description: 'Now let\'s look at how to manage all your spellbooks. We\'ll go to the Spellbooks page.',
        placement: 'center',
        beforeStep: 'navigate-to-spellbooks',
        requiredView: 'spellbooks',
      },
      // SPELLBOOKS LIST PHASE
      {
        id: 'spellbooks-create',
        targetSelector: '[data-testid="btn-create-spellbook"]',
        title: 'Create a Spellbook',
        description: 'Create new spellbooks for each character or campaign. You can set spellcasting ability, attack modifier, and spell slots.',
        placement: 'bottom',
        requiredView: 'spellbooks',
      },
      {
        id: 'spellbooks-search',
        targetSelector: '.spellbook-search',
        title: 'Search Spellbooks',
        description: 'Have many spellbooks? Search by name to quickly find the one you need.',
        placement: 'bottom',
        requiredView: 'spellbooks',
      },
      {
        id: 'spellbooks-list',
        targetSelector: '.spellbook-list-table',
        title: 'Your Spellbooks',
        description: 'Each row is a spellbook. Tap to open, or long-press for quick actions like edit and delete.',
        desktopDescription: 'Each row is a spellbook. Click a row to open it and manage its spells.',
        placement: 'top',
        mobilePlacement: 'top',
        requiredView: 'spellbooks',
      },
      {
        id: 'spellbooks-import-export',
        targetSelector: '[data-testid="btn-export-spellbooks"]',
        title: 'Import & Export',
        description: 'Backup your spellbooks or share them with friends. Uses JSON format that can be re-imported anytime.',
        placement: 'bottom',
        requiredView: 'spellbooks',
      },
      {
        id: 'spellbooks-complete',
        title: 'You\'re All Set!',
        description: 'You now know how to manage your spellbooks! Happy spellcasting!',
        placement: 'center',
        requiredView: 'spellbooks',
      },
    ],
  },
};

// Tours shown in the Help menu (excludes 'welcome' which is only for first-time users)
export const TOUR_ORDER: TourId[] = [
  'browse-spells',
  'spellbooks',
];
