import { Tour, TourId } from '../types/tutorial';

export const TOURS: Record<TourId, Tour> = {
  navigation: {
    id: 'navigation',
    name: 'App Navigation',
    description: 'Learn how to navigate between views',
    requiredView: 'browse',
    steps: [
      {
        id: 'nav-welcome',
        targetSelector: '.app-title',
        title: 'Welcome to The Spellbookery',
        description: 'This is your D&D spell management tool. Let\'s learn how to navigate around.',
        placement: 'bottom',
      },
      {
        id: 'nav-browse',
        targetSelector: '.app-nav .nav-link:first-child',
        title: 'Browse Spells',
        description: 'Click here to search and explore all D&D spells. This is where you\'ll find spells to add to your spellbooks.',
        placement: 'bottom',
      },
      {
        id: 'nav-spellbooks',
        targetSelector: '[data-testid="nav-spellbooks"]',
        title: 'My Spellbooks',
        description: 'Your personal spellbook collection lives here. Create spellbooks for different characters or campaigns.',
        placement: 'bottom',
      },
      {
        id: 'nav-utilities',
        targetSelector: '.nav-link-help',
        title: 'Need Help?',
        description: 'Click here anytime to access these tutorials again, plus About info, feedback, and theme options.',
        placement: 'bottom',
      },
    ],
  },
  'browse-spells': {
    id: 'browse-spells',
    name: 'Browse Spells',
    description: 'Search, filter, and add spells to your spellbooks',
    requiredView: 'browse',
    steps: [
      {
        id: 'browse-search',
        targetSelector: '.search-input',
        title: 'Search Spells',
        description: 'Type a spell name to quickly find it. Try searching for "Fireball" or "Cure Wounds".',
        placement: 'bottom',
      },
      {
        id: 'browse-filters',
        targetSelector: '.filter-header',
        title: 'Advanced Filters',
        description: 'Filter spells by level, school, class, and more. Perfect for finding spells that match your character.',
        placement: 'bottom',
      },
      {
        id: 'browse-table',
        targetSelector: '.spell-table',
        title: 'Spell List',
        description: 'Browse all D&D spells here. Use the sort buttons above to organize them. Tap any spell to see its full details.',
        desktopDescription: 'Browse all D&D spells here. Click any column header to sort. Click a spell row to see its full details.',
        placement: 'top',
      },
      {
        id: 'browse-checkbox',
        targetSelector: '.spell-row .checkbox-col input',
        title: 'Select Spells',
        description: 'Check the box to select spells for adding to a spellbook. You can select multiple spells at once!',
        placement: 'bottom',
        desktopPlacement: 'right',
      },
      {
        id: 'browse-select-all',
        targetSelector: '[data-testid="btn-select-all-mobile"]',
        title: 'Bulk Selection',
        description: 'Select or deselect all visible spells at once. Great when combined with filters!',
        placement: 'bottom',
      },
      {
        id: 'browse-add',
        targetSelector: '[data-testid="btn-add-selected"]',
        title: 'Add to Spellbook',
        description: 'Once you\'ve selected spells, click here to add them to a spellbook. You\'ll choose which spellbook or create a new one.',
        placement: 'bottom',
      },
      {
        id: 'browse-complete',
        title: 'You\'re Ready!',
        description: 'Now you know how to browse and select spells. Try the "Manage Spellbooks" tour next to learn about creating spellbooks!',
        placement: 'center',
      },
    ],
  },
  'spellbooks-list': {
    id: 'spellbooks-list',
    name: 'Manage Spellbooks',
    description: 'Create, edit, and organize your spellbook collection',
    requiredView: 'spellbooks',
    steps: [
      {
        id: 'spellbooks-create',
        targetSelector: '[data-testid="btn-create-spellbook"]',
        title: 'Create a Spellbook',
        description: 'Start here! Create a new spellbook for your character or campaign. You can set spellcasting ability and stats.',
        placement: 'bottom',
      },
      {
        id: 'spellbooks-search',
        targetSelector: '.spellbook-search',
        title: 'Search Spellbooks',
        description: 'Have many spellbooks? Search by name to quickly find the one you need.',
        placement: 'bottom',
      },
      {
        id: 'spellbooks-list',
        targetSelector: '.spellbook-list-table',
        title: 'Your Spellbooks',
        description: 'Each row is a spellbook. Tap to open, or long-press for quick actions like edit and delete.',
        desktopDescription: 'Each row is a spellbook. Click a row to open it and manage its spells.',
        placement: 'top',
      },
      {
        id: 'spellbooks-import-export',
        targetSelector: '[data-testid="btn-export-spellbooks"]',
        title: 'Import & Export',
        description: 'Backup your spellbooks or share them with friends. Uses JSON format that can be re-imported anytime.',
        placement: 'bottom',
      },
      {
        id: 'spellbooks-complete',
        title: 'All Set!',
        description: 'Now you know how to manage spellbooks. Open a spellbook to learn about preparing spells and tracking spell slots!',
        placement: 'center',
      },
    ],
  },
  'spellbook-detail': {
    id: 'spellbook-detail',
    name: 'Spellbook Details',
    description: 'Prepare spells and manage your spellbook contents',
    requiredView: 'spellbook-detail',
    steps: [
      {
        id: 'detail-header',
        targetSelector: '.spellbook-detail-header',
        title: 'Spellbook Overview',
        description: 'Your spellbook\'s name and stats are shown here. Use the buttons to edit, copy, or delete this spellbook.',
        placement: 'bottom',
      },
      {
        id: 'detail-slots',
        targetSelector: '.spell-slots-display',
        title: 'Spell Slots',
        description: 'Track your available spell slots by level. Set these in the Edit menu to match your character.',
        placement: 'bottom',
      },
      {
        id: 'detail-spells',
        targetSelector: '.spellbook-table',
        title: 'Your Spells',
        description: 'All spells in this spellbook. Tap any spell for details, or use checkboxes to select multiple.',
        desktopDescription: 'All spells in this spellbook. Click any row to see full details and toggle prepared status.',
        placement: 'top',
      },
      {
        id: 'detail-prepared-toggle',
        targetSelector: '[data-testid="btn-prep-selected"]',
        title: 'Prepare Spells',
        description: 'Select spells using checkboxes, then click Prep to mark them as prepared. Prepared spells are highlighted in gold!',
        placement: 'bottom',
      },
      {
        id: 'detail-prepared-filter',
        targetSelector: '[data-testid="filter-prepared-only"]',
        title: 'Filter by Prepared',
        description: 'Toggle this to show only your prepared spells. Great for during gameplay when you need quick access.',
        placement: 'bottom',
      },
      {
        id: 'detail-remove',
        targetSelector: '[data-testid="btn-remove-selected"]',
        title: 'Remove Spells',
        description: 'Select spells and click Remove to take them out of this spellbook. You can always add them back later.',
        placement: 'bottom',
      },
      {
        id: 'detail-back',
        targetSelector: '[data-testid="back-to-spellbooks"]',
        title: 'Navigation',
        description: 'Click here to go back to your spellbook list when you\'re done.',
        placement: 'bottom',
      },
      {
        id: 'detail-complete',
        title: 'You\'re All Set!',
        description: 'You now know how to use The Spellbookery! Happy spellcasting!',
        placement: 'center',
      },
    ],
  },
};

export const TOUR_ORDER: TourId[] = [
  'navigation',
  'browse-spells',
  'spellbooks-list',
  'spellbook-detail',
];
